"""move unit to ingredients

Revision ID: 09eb11ea2d0b
Revises: 60b84be8a078
Create Date: 2026-03-17 20:09:35.986832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eb11ea2d0b'
down_revision: Union[str, Sequence[str], None] = '60b84be8a078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit', sa.String(length=30), nullable=False))
    op.drop_column('price_ingredients', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_ingredients', sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('ingredients', 'unit')
    # ### end Alembic commands ###
