"""create ingredient stock table

Revision ID: 4cd391000c5a
Revises: 09eb11ea2d0b
Create Date: 2026-03-18 19:19:20.070026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd391000c5a'
down_revision: Union[str, Sequence[str], None] = '09eb11ea2d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_stock_id'), 'ingredient_stock', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_stock_ingredient_id'), 'ingredient_stock', ['ingredient_id'], unique=False)
    op.drop_column('price_ingredients', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_ingredients', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ingredient_stock_ingredient_id'), table_name='ingredient_stock')
    op.drop_index(op.f('ix_ingredient_stock_id'), table_name='ingredient_stock')
    op.drop_table('ingredient_stock')
    # ### end Alembic commands ###
