"""new version

Revision ID: 5356a8879dbe
Revises: a7862bb9029c
Create Date: 2026-03-19 17:39:27.238566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5356a8879dbe'
down_revision: Union[str, Sequence[str], None] = 'a7862bb9029c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('planned_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_batches_recipe_id'), 'batches', ['recipe_id'], unique=False)
    op.create_table('ingredients_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_price_id'), 'ingredients_price', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_price_ingredient_id'), 'ingredients_price', ['ingredient_id'], unique=False)
    op.create_table('ingredients_stock_moviments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type_moviment', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_stock_moviments_id'), 'ingredients_stock_moviments', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_stock_moviments_ingredient_id'), 'ingredients_stock_moviments', ['ingredient_id'], unique=False)
    op.drop_index(op.f('ix_price_ingredients_id'), table_name='price_ingredients')
    op.drop_index(op.f('ix_price_ingredients_ingredient_id'), table_name='price_ingredients')
    op.drop_table('price_ingredients')
    op.drop_index(op.f('ix_ingredient_stock_id'), table_name='ingredient_stock')
    op.drop_index(op.f('ix_ingredient_stock_ingredient_id'), table_name='ingredient_stock')
    op.drop_table('ingredient_stock')
    op.add_column('ingredients', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('quantity_base', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('stock_units', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'stock_units')
    op.drop_column('recipes', 'quantity_base')
    op.drop_column('ingredients', 'stock')
    op.create_table('ingredient_stock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('ingredient_stock_ingredient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredient_stock_pkey'))
    )
    op.create_index(op.f('ix_ingredient_stock_ingredient_id'), 'ingredient_stock', ['ingredient_id'], unique=True)
    op.create_index(op.f('ix_ingredient_stock_id'), 'ingredient_stock', ['id'], unique=False)
    op.create_table('price_ingredients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('price_ingredients_ingredient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('price_ingredients_pkey'))
    )
    op.create_index(op.f('ix_price_ingredients_ingredient_id'), 'price_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_price_ingredients_id'), 'price_ingredients', ['id'], unique=False)
    op.drop_index(op.f('ix_ingredients_stock_moviments_ingredient_id'), table_name='ingredients_stock_moviments')
    op.drop_index(op.f('ix_ingredients_stock_moviments_id'), table_name='ingredients_stock_moviments')
    op.drop_table('ingredients_stock_moviments')
    op.drop_index(op.f('ix_ingredients_price_ingredient_id'), table_name='ingredients_price')
    op.drop_index(op.f('ix_ingredients_price_id'), table_name='ingredients_price')
    op.drop_table('ingredients_price')
    op.drop_index(op.f('ix_batches_recipe_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
