"""deleted status in batch and changed nullable in end_date

Revision ID: 87db27dd0549
Revises: 0e818580973c
Create Date: 2026-03-24 19:19:58.471748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87db27dd0549'
down_revision: Union[str, Sequence[str], None] = '0e818580973c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('batches', 'status')
    op.alter_column('ingredients_stock_moviments', 'type_movement',
               existing_type=postgresql.ENUM('IN', 'OUT', 'ADJUSTMENT', name='movement_type'),
               nullable=True)
    op.alter_column('recipes', 'stock_units',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'stock_units',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingredients_stock_moviments', 'type_movement',
               existing_type=postgresql.ENUM('IN', 'OUT', 'ADJUSTMENT', name='movement_type'),
               nullable=False)
    op.add_column('batches', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.alter_column('batches', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
