"""modificated ingredient stock table

Revision ID: a7862bb9029c
Revises: c03a1e55f595
Create Date: 2026-03-18 20:30:09.734167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7862bb9029c'
down_revision: Union[str, Sequence[str], None] = 'c03a1e55f595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_stock', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_stock', 'date')
    # ### end Alembic commands ###
