"""modificated ingredient stock table

Revision ID: c03a1e55f595
Revises: 4cd391000c5a
Create Date: 2026-03-18 19:36:07.790758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03a1e55f595'
down_revision: Union[str, Sequence[str], None] = '4cd391000c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_stock_ingredient_id'), table_name='ingredient_stock')
    op.create_index(op.f('ix_ingredient_stock_ingredient_id'), 'ingredient_stock', ['ingredient_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_stock_ingredient_id'), table_name='ingredient_stock')
    op.create_index(op.f('ix_ingredient_stock_ingredient_id'), 'ingredient_stock', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###
